Fix the todo, warning sign not rendered
graphql/graphql-http pull request #126
Opened 2024-08-26 17:57 UTC by h3ssan

## Overview

Fix the todo of rendering the unicode character as different one, since `(` ⚠️ `)` it's not widely supported across the browsers, therefore I used `(` ❗️ `)` instead, since it's widely supported across all browsers.

## Screenshots

### Old Code

![old code](https://i.imgur.com/8P6t2SV.png)

### Newer Code

![new code](https://i.imgur.com/UYGFuQL.png)

2024-08-27 10:12 UTC, enisdenjo approved these changes
Cheers @h3ssan, you're doing a great job with all the PRs! We are very grateful.

2024-08-27 10:12 UTC, enisdenjo requested changes
Please update the test snapshots.

2024-08-27 10:15 UTC, h3ssan commented
> Please update the test snapshots.

Sorry, didn’t understand.

2024-08-27 10:26 UTC, h3ssan commented
> Please update the test snapshots.

Done, thank you

2024-08-27 10:39 UTC, merged

2024-11-07 14:25 UTC, enisdenjo commented
:tada: This PR is included in version 1.22.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/graphql-http/v/1.22.2)
- [GitHub release](https://github.com/graphql/graphql-http/releases/tag/v1.22.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: