Add CONTRIBUTING.md
graphql/graphql-http pull request #64
Opened 2023-03-21 17:24 UTC by spawnia

Feel free to push any changes you would like directly to the branch.

2023-03-22 09:40 UTC, enisdenjo requested changes

2023-03-22 09:51 UTC, spawnia commented on package.json
> +    "lint:fix": "yarn lint:eslint --fix && prettier --write .",
That will not work, as `lint:prettier` already defines `--check`.

2023-03-22 09:53 UTC, enisdenjo commented on package.json
> +    "lint:fix": "yarn lint:eslint --fix && prettier --write .",
Try it.

2023-03-22 10:13 UTC, spawnia commented on package.json
> +    "lint:fix": "yarn lint:eslint --fix && prettier --write .",
You are right, that surprised me.

2023-03-27 09:34 UTC, enisdenjo approved these changes

2023-03-27 10:03 UTC, merged